# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/372/bin/cmake

# The command to remove a file.
RM = /snap/cmake/372/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/deandre/Argentum-Taller

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/deandre/Argentum-Taller

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/372/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/372/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deandre/Argentum-Taller/CMakeFiles /home/deandre/Argentum-Taller/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deandre/Argentum-Taller/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

src/client/Banker.o: src/client/Banker.cpp.o

.PHONY : src/client/Banker.o

# target to build an object file
src/client/Banker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Banker.cpp.o
.PHONY : src/client/Banker.cpp.o

src/client/Banker.i: src/client/Banker.cpp.i

.PHONY : src/client/Banker.i

# target to preprocess a source file
src/client/Banker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Banker.cpp.i
.PHONY : src/client/Banker.cpp.i

src/client/Banker.s: src/client/Banker.cpp.s

.PHONY : src/client/Banker.s

# target to generate assembly for a file
src/client/Banker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Banker.cpp.s
.PHONY : src/client/Banker.cpp.s

src/client/Camera.o: src/client/Camera.cpp.o

.PHONY : src/client/Camera.o

# target to build an object file
src/client/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Camera.cpp.o
.PHONY : src/client/Camera.cpp.o

src/client/Camera.i: src/client/Camera.cpp.i

.PHONY : src/client/Camera.i

# target to preprocess a source file
src/client/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Camera.cpp.i
.PHONY : src/client/Camera.cpp.i

src/client/Camera.s: src/client/Camera.cpp.s

.PHONY : src/client/Camera.s

# target to generate assembly for a file
src/client/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Camera.cpp.s
.PHONY : src/client/Camera.cpp.s

src/client/Chrono.o: src/client/Chrono.cpp.o

.PHONY : src/client/Chrono.o

# target to build an object file
src/client/Chrono.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Chrono.cpp.o
.PHONY : src/client/Chrono.cpp.o

src/client/Chrono.i: src/client/Chrono.cpp.i

.PHONY : src/client/Chrono.i

# target to preprocess a source file
src/client/Chrono.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Chrono.cpp.i
.PHONY : src/client/Chrono.cpp.i

src/client/Chrono.s: src/client/Chrono.cpp.s

.PHONY : src/client/Chrono.s

# target to generate assembly for a file
src/client/Chrono.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Chrono.cpp.s
.PHONY : src/client/Chrono.cpp.s

src/client/Exception.o: src/client/Exception.cpp.o

.PHONY : src/client/Exception.o

# target to build an object file
src/client/Exception.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Exception.cpp.o
.PHONY : src/client/Exception.cpp.o

src/client/Exception.i: src/client/Exception.cpp.i

.PHONY : src/client/Exception.i

# target to preprocess a source file
src/client/Exception.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Exception.cpp.i
.PHONY : src/client/Exception.cpp.i

src/client/Exception.s: src/client/Exception.cpp.s

.PHONY : src/client/Exception.s

# target to generate assembly for a file
src/client/Exception.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Exception.cpp.s
.PHONY : src/client/Exception.cpp.s

src/client/Font.o: src/client/Font.cpp.o

.PHONY : src/client/Font.o

# target to build an object file
src/client/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Font.cpp.o
.PHONY : src/client/Font.cpp.o

src/client/Font.i: src/client/Font.cpp.i

.PHONY : src/client/Font.i

# target to preprocess a source file
src/client/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Font.cpp.i
.PHONY : src/client/Font.cpp.i

src/client/Font.s: src/client/Font.cpp.s

.PHONY : src/client/Font.s

# target to generate assembly for a file
src/client/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Font.cpp.s
.PHONY : src/client/Font.cpp.s

src/client/GameMap.o: src/client/GameMap.cpp.o

.PHONY : src/client/GameMap.o

# target to build an object file
src/client/GameMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/GameMap.cpp.o
.PHONY : src/client/GameMap.cpp.o

src/client/GameMap.i: src/client/GameMap.cpp.i

.PHONY : src/client/GameMap.i

# target to preprocess a source file
src/client/GameMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/GameMap.cpp.i
.PHONY : src/client/GameMap.cpp.i

src/client/GameMap.s: src/client/GameMap.cpp.s

.PHONY : src/client/GameMap.s

# target to generate assembly for a file
src/client/GameMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/GameMap.cpp.s
.PHONY : src/client/GameMap.cpp.s

src/client/Goblin.o: src/client/Goblin.cpp.o

.PHONY : src/client/Goblin.o

# target to build an object file
src/client/Goblin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Goblin.cpp.o
.PHONY : src/client/Goblin.cpp.o

src/client/Goblin.i: src/client/Goblin.cpp.i

.PHONY : src/client/Goblin.i

# target to preprocess a source file
src/client/Goblin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Goblin.cpp.i
.PHONY : src/client/Goblin.cpp.i

src/client/Goblin.s: src/client/Goblin.cpp.s

.PHONY : src/client/Goblin.s

# target to generate assembly for a file
src/client/Goblin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Goblin.cpp.s
.PHONY : src/client/Goblin.cpp.s

src/client/Items/AshStick.o: src/client/Items/AshStick.cpp.o

.PHONY : src/client/Items/AshStick.o

# target to build an object file
src/client/Items/AshStick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/AshStick.cpp.o
.PHONY : src/client/Items/AshStick.cpp.o

src/client/Items/AshStick.i: src/client/Items/AshStick.cpp.i

.PHONY : src/client/Items/AshStick.i

# target to preprocess a source file
src/client/Items/AshStick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/AshStick.cpp.i
.PHONY : src/client/Items/AshStick.cpp.i

src/client/Items/AshStick.s: src/client/Items/AshStick.cpp.s

.PHONY : src/client/Items/AshStick.s

# target to generate assembly for a file
src/client/Items/AshStick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/AshStick.cpp.s
.PHONY : src/client/Items/AshStick.cpp.s

src/client/Items/Ax.o: src/client/Items/Ax.cpp.o

.PHONY : src/client/Items/Ax.o

# target to build an object file
src/client/Items/Ax.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Ax.cpp.o
.PHONY : src/client/Items/Ax.cpp.o

src/client/Items/Ax.i: src/client/Items/Ax.cpp.i

.PHONY : src/client/Items/Ax.i

# target to preprocess a source file
src/client/Items/Ax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Ax.cpp.i
.PHONY : src/client/Items/Ax.cpp.i

src/client/Items/Ax.s: src/client/Items/Ax.cpp.s

.PHONY : src/client/Items/Ax.s

# target to generate assembly for a file
src/client/Items/Ax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Ax.cpp.s
.PHONY : src/client/Items/Ax.cpp.s

src/client/Items/BankerBody.o: src/client/Items/BankerBody.cpp.o

.PHONY : src/client/Items/BankerBody.o

# target to build an object file
src/client/Items/BankerBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BankerBody.cpp.o
.PHONY : src/client/Items/BankerBody.cpp.o

src/client/Items/BankerBody.i: src/client/Items/BankerBody.cpp.i

.PHONY : src/client/Items/BankerBody.i

# target to preprocess a source file
src/client/Items/BankerBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BankerBody.cpp.i
.PHONY : src/client/Items/BankerBody.cpp.i

src/client/Items/BankerBody.s: src/client/Items/BankerBody.cpp.s

.PHONY : src/client/Items/BankerBody.s

# target to generate assembly for a file
src/client/Items/BankerBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BankerBody.cpp.s
.PHONY : src/client/Items/BankerBody.cpp.s

src/client/Items/BlueCommonBody.o: src/client/Items/BlueCommonBody.cpp.o

.PHONY : src/client/Items/BlueCommonBody.o

# target to build an object file
src/client/Items/BlueCommonBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BlueCommonBody.cpp.o
.PHONY : src/client/Items/BlueCommonBody.cpp.o

src/client/Items/BlueCommonBody.i: src/client/Items/BlueCommonBody.cpp.i

.PHONY : src/client/Items/BlueCommonBody.i

# target to preprocess a source file
src/client/Items/BlueCommonBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BlueCommonBody.cpp.i
.PHONY : src/client/Items/BlueCommonBody.cpp.i

src/client/Items/BlueCommonBody.s: src/client/Items/BlueCommonBody.cpp.s

.PHONY : src/client/Items/BlueCommonBody.s

# target to generate assembly for a file
src/client/Items/BlueCommonBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BlueCommonBody.cpp.s
.PHONY : src/client/Items/BlueCommonBody.cpp.s

src/client/Items/BlueTunic.o: src/client/Items/BlueTunic.cpp.o

.PHONY : src/client/Items/BlueTunic.o

# target to build an object file
src/client/Items/BlueTunic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BlueTunic.cpp.o
.PHONY : src/client/Items/BlueTunic.cpp.o

src/client/Items/BlueTunic.i: src/client/Items/BlueTunic.cpp.i

.PHONY : src/client/Items/BlueTunic.i

# target to preprocess a source file
src/client/Items/BlueTunic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BlueTunic.cpp.i
.PHONY : src/client/Items/BlueTunic.cpp.i

src/client/Items/BlueTunic.s: src/client/Items/BlueTunic.cpp.s

.PHONY : src/client/Items/BlueTunic.s

# target to generate assembly for a file
src/client/Items/BlueTunic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/BlueTunic.cpp.s
.PHONY : src/client/Items/BlueTunic.cpp.s

src/client/Items/CompoundArc.o: src/client/Items/CompoundArc.cpp.o

.PHONY : src/client/Items/CompoundArc.o

# target to build an object file
src/client/Items/CompoundArc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/CompoundArc.cpp.o
.PHONY : src/client/Items/CompoundArc.cpp.o

src/client/Items/CompoundArc.i: src/client/Items/CompoundArc.cpp.i

.PHONY : src/client/Items/CompoundArc.i

# target to preprocess a source file
src/client/Items/CompoundArc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/CompoundArc.cpp.i
.PHONY : src/client/Items/CompoundArc.cpp.i

src/client/Items/CompoundArc.s: src/client/Items/CompoundArc.cpp.s

.PHONY : src/client/Items/CompoundArc.s

# target to generate assembly for a file
src/client/Items/CompoundArc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/CompoundArc.cpp.s
.PHONY : src/client/Items/CompoundArc.cpp.s

src/client/Items/Crosier.o: src/client/Items/Crosier.cpp.o

.PHONY : src/client/Items/Crosier.o

# target to build an object file
src/client/Items/Crosier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Crosier.cpp.o
.PHONY : src/client/Items/Crosier.cpp.o

src/client/Items/Crosier.i: src/client/Items/Crosier.cpp.i

.PHONY : src/client/Items/Crosier.i

# target to preprocess a source file
src/client/Items/Crosier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Crosier.cpp.i
.PHONY : src/client/Items/Crosier.cpp.i

src/client/Items/Crosier.s: src/client/Items/Crosier.cpp.s

.PHONY : src/client/Items/Crosier.s

# target to generate assembly for a file
src/client/Items/Crosier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Crosier.cpp.s
.PHONY : src/client/Items/Crosier.cpp.s

src/client/Items/DwarfHead.o: src/client/Items/DwarfHead.cpp.o

.PHONY : src/client/Items/DwarfHead.o

# target to build an object file
src/client/Items/DwarfHead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/DwarfHead.cpp.o
.PHONY : src/client/Items/DwarfHead.cpp.o

src/client/Items/DwarfHead.i: src/client/Items/DwarfHead.cpp.i

.PHONY : src/client/Items/DwarfHead.i

# target to preprocess a source file
src/client/Items/DwarfHead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/DwarfHead.cpp.i
.PHONY : src/client/Items/DwarfHead.cpp.i

src/client/Items/DwarfHead.s: src/client/Items/DwarfHead.cpp.s

.PHONY : src/client/Items/DwarfHead.s

# target to generate assembly for a file
src/client/Items/DwarfHead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/DwarfHead.cpp.s
.PHONY : src/client/Items/DwarfHead.cpp.s

src/client/Items/ElfHead.o: src/client/Items/ElfHead.cpp.o

.PHONY : src/client/Items/ElfHead.o

# target to build an object file
src/client/Items/ElfHead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ElfHead.cpp.o
.PHONY : src/client/Items/ElfHead.cpp.o

src/client/Items/ElfHead.i: src/client/Items/ElfHead.cpp.i

.PHONY : src/client/Items/ElfHead.i

# target to preprocess a source file
src/client/Items/ElfHead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ElfHead.cpp.i
.PHONY : src/client/Items/ElfHead.cpp.i

src/client/Items/ElfHead.s: src/client/Items/ElfHead.cpp.s

.PHONY : src/client/Items/ElfHead.s

# target to generate assembly for a file
src/client/Items/ElfHead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ElfHead.cpp.s
.PHONY : src/client/Items/ElfHead.cpp.s

src/client/Items/ElficFlaute.o: src/client/Items/ElficFlaute.cpp.o

.PHONY : src/client/Items/ElficFlaute.o

# target to build an object file
src/client/Items/ElficFlaute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ElficFlaute.cpp.o
.PHONY : src/client/Items/ElficFlaute.cpp.o

src/client/Items/ElficFlaute.i: src/client/Items/ElficFlaute.cpp.i

.PHONY : src/client/Items/ElficFlaute.i

# target to preprocess a source file
src/client/Items/ElficFlaute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ElficFlaute.cpp.i
.PHONY : src/client/Items/ElficFlaute.cpp.i

src/client/Items/ElficFlaute.s: src/client/Items/ElficFlaute.cpp.s

.PHONY : src/client/Items/ElficFlaute.s

# target to generate assembly for a file
src/client/Items/ElficFlaute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ElficFlaute.cpp.s
.PHONY : src/client/Items/ElficFlaute.cpp.s

src/client/Items/GhostBody.o: src/client/Items/GhostBody.cpp.o

.PHONY : src/client/Items/GhostBody.o

# target to build an object file
src/client/Items/GhostBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GhostBody.cpp.o
.PHONY : src/client/Items/GhostBody.cpp.o

src/client/Items/GhostBody.i: src/client/Items/GhostBody.cpp.i

.PHONY : src/client/Items/GhostBody.i

# target to preprocess a source file
src/client/Items/GhostBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GhostBody.cpp.i
.PHONY : src/client/Items/GhostBody.cpp.i

src/client/Items/GhostBody.s: src/client/Items/GhostBody.cpp.s

.PHONY : src/client/Items/GhostBody.s

# target to generate assembly for a file
src/client/Items/GhostBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GhostBody.cpp.s
.PHONY : src/client/Items/GhostBody.cpp.s

src/client/Items/GnarledStick.o: src/client/Items/GnarledStick.cpp.o

.PHONY : src/client/Items/GnarledStick.o

# target to build an object file
src/client/Items/GnarledStick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GnarledStick.cpp.o
.PHONY : src/client/Items/GnarledStick.cpp.o

src/client/Items/GnarledStick.i: src/client/Items/GnarledStick.cpp.i

.PHONY : src/client/Items/GnarledStick.i

# target to preprocess a source file
src/client/Items/GnarledStick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GnarledStick.cpp.i
.PHONY : src/client/Items/GnarledStick.cpp.i

src/client/Items/GnarledStick.s: src/client/Items/GnarledStick.cpp.s

.PHONY : src/client/Items/GnarledStick.s

# target to generate assembly for a file
src/client/Items/GnarledStick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GnarledStick.cpp.s
.PHONY : src/client/Items/GnarledStick.cpp.s

src/client/Items/GnomeHead.o: src/client/Items/GnomeHead.cpp.o

.PHONY : src/client/Items/GnomeHead.o

# target to build an object file
src/client/Items/GnomeHead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GnomeHead.cpp.o
.PHONY : src/client/Items/GnomeHead.cpp.o

src/client/Items/GnomeHead.i: src/client/Items/GnomeHead.cpp.i

.PHONY : src/client/Items/GnomeHead.i

# target to preprocess a source file
src/client/Items/GnomeHead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GnomeHead.cpp.i
.PHONY : src/client/Items/GnomeHead.cpp.i

src/client/Items/GnomeHead.s: src/client/Items/GnomeHead.cpp.s

.PHONY : src/client/Items/GnomeHead.s

# target to generate assembly for a file
src/client/Items/GnomeHead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GnomeHead.cpp.s
.PHONY : src/client/Items/GnomeHead.cpp.s

src/client/Items/GoblinBody.o: src/client/Items/GoblinBody.cpp.o

.PHONY : src/client/Items/GoblinBody.o

# target to build an object file
src/client/Items/GoblinBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GoblinBody.cpp.o
.PHONY : src/client/Items/GoblinBody.cpp.o

src/client/Items/GoblinBody.i: src/client/Items/GoblinBody.cpp.i

.PHONY : src/client/Items/GoblinBody.i

# target to preprocess a source file
src/client/Items/GoblinBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GoblinBody.cpp.i
.PHONY : src/client/Items/GoblinBody.cpp.i

src/client/Items/GoblinBody.s: src/client/Items/GoblinBody.cpp.s

.PHONY : src/client/Items/GoblinBody.s

# target to generate assembly for a file
src/client/Items/GoblinBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GoblinBody.cpp.s
.PHONY : src/client/Items/GoblinBody.cpp.s

src/client/Items/GreenCommonBody.o: src/client/Items/GreenCommonBody.cpp.o

.PHONY : src/client/Items/GreenCommonBody.o

# target to build an object file
src/client/Items/GreenCommonBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GreenCommonBody.cpp.o
.PHONY : src/client/Items/GreenCommonBody.cpp.o

src/client/Items/GreenCommonBody.i: src/client/Items/GreenCommonBody.cpp.i

.PHONY : src/client/Items/GreenCommonBody.i

# target to preprocess a source file
src/client/Items/GreenCommonBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GreenCommonBody.cpp.i
.PHONY : src/client/Items/GreenCommonBody.cpp.i

src/client/Items/GreenCommonBody.s: src/client/Items/GreenCommonBody.cpp.s

.PHONY : src/client/Items/GreenCommonBody.s

# target to generate assembly for a file
src/client/Items/GreenCommonBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/GreenCommonBody.cpp.s
.PHONY : src/client/Items/GreenCommonBody.cpp.s

src/client/Items/Hammer.o: src/client/Items/Hammer.cpp.o

.PHONY : src/client/Items/Hammer.o

# target to build an object file
src/client/Items/Hammer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Hammer.cpp.o
.PHONY : src/client/Items/Hammer.cpp.o

src/client/Items/Hammer.i: src/client/Items/Hammer.cpp.i

.PHONY : src/client/Items/Hammer.i

# target to preprocess a source file
src/client/Items/Hammer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Hammer.cpp.i
.PHONY : src/client/Items/Hammer.cpp.i

src/client/Items/Hammer.s: src/client/Items/Hammer.cpp.s

.PHONY : src/client/Items/Hammer.s

# target to generate assembly for a file
src/client/Items/Hammer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Hammer.cpp.s
.PHONY : src/client/Items/Hammer.cpp.s

src/client/Items/Hood.o: src/client/Items/Hood.cpp.o

.PHONY : src/client/Items/Hood.o

# target to build an object file
src/client/Items/Hood.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Hood.cpp.o
.PHONY : src/client/Items/Hood.cpp.o

src/client/Items/Hood.i: src/client/Items/Hood.cpp.i

.PHONY : src/client/Items/Hood.i

# target to preprocess a source file
src/client/Items/Hood.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Hood.cpp.i
.PHONY : src/client/Items/Hood.cpp.i

src/client/Items/Hood.s: src/client/Items/Hood.cpp.s

.PHONY : src/client/Items/Hood.s

# target to generate assembly for a file
src/client/Items/Hood.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/Hood.cpp.s
.PHONY : src/client/Items/Hood.cpp.s

src/client/Items/HumanHead.o: src/client/Items/HumanHead.cpp.o

.PHONY : src/client/Items/HumanHead.o

# target to build an object file
src/client/Items/HumanHead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/HumanHead.cpp.o
.PHONY : src/client/Items/HumanHead.cpp.o

src/client/Items/HumanHead.i: src/client/Items/HumanHead.cpp.i

.PHONY : src/client/Items/HumanHead.i

# target to preprocess a source file
src/client/Items/HumanHead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/HumanHead.cpp.i
.PHONY : src/client/Items/HumanHead.cpp.i

src/client/Items/HumanHead.s: src/client/Items/HumanHead.cpp.s

.PHONY : src/client/Items/HumanHead.s

# target to generate assembly for a file
src/client/Items/HumanHead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/HumanHead.cpp.s
.PHONY : src/client/Items/HumanHead.cpp.s

src/client/Items/IronHelmet.o: src/client/Items/IronHelmet.cpp.o

.PHONY : src/client/Items/IronHelmet.o

# target to build an object file
src/client/Items/IronHelmet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/IronHelmet.cpp.o
.PHONY : src/client/Items/IronHelmet.cpp.o

src/client/Items/IronHelmet.i: src/client/Items/IronHelmet.cpp.i

.PHONY : src/client/Items/IronHelmet.i

# target to preprocess a source file
src/client/Items/IronHelmet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/IronHelmet.cpp.i
.PHONY : src/client/Items/IronHelmet.cpp.i

src/client/Items/IronHelmet.s: src/client/Items/IronHelmet.cpp.s

.PHONY : src/client/Items/IronHelmet.s

# target to generate assembly for a file
src/client/Items/IronHelmet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/IronHelmet.cpp.s
.PHONY : src/client/Items/IronHelmet.cpp.s

src/client/Items/IronShield.o: src/client/Items/IronShield.cpp.o

.PHONY : src/client/Items/IronShield.o

# target to build an object file
src/client/Items/IronShield.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/IronShield.cpp.o
.PHONY : src/client/Items/IronShield.cpp.o

src/client/Items/IronShield.i: src/client/Items/IronShield.cpp.i

.PHONY : src/client/Items/IronShield.i

# target to preprocess a source file
src/client/Items/IronShield.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/IronShield.cpp.i
.PHONY : src/client/Items/IronShield.cpp.i

src/client/Items/IronShield.s: src/client/Items/IronShield.cpp.s

.PHONY : src/client/Items/IronShield.s

# target to generate assembly for a file
src/client/Items/IronShield.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/IronShield.cpp.s
.PHONY : src/client/Items/IronShield.cpp.s

src/client/Items/LeatherArmor.o: src/client/Items/LeatherArmor.cpp.o

.PHONY : src/client/Items/LeatherArmor.o

# target to build an object file
src/client/Items/LeatherArmor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/LeatherArmor.cpp.o
.PHONY : src/client/Items/LeatherArmor.cpp.o

src/client/Items/LeatherArmor.i: src/client/Items/LeatherArmor.cpp.i

.PHONY : src/client/Items/LeatherArmor.i

# target to preprocess a source file
src/client/Items/LeatherArmor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/LeatherArmor.cpp.i
.PHONY : src/client/Items/LeatherArmor.cpp.i

src/client/Items/LeatherArmor.s: src/client/Items/LeatherArmor.cpp.s

.PHONY : src/client/Items/LeatherArmor.s

# target to generate assembly for a file
src/client/Items/LeatherArmor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/LeatherArmor.cpp.s
.PHONY : src/client/Items/LeatherArmor.cpp.s

src/client/Items/LongSword.o: src/client/Items/LongSword.cpp.o

.PHONY : src/client/Items/LongSword.o

# target to build an object file
src/client/Items/LongSword.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/LongSword.cpp.o
.PHONY : src/client/Items/LongSword.cpp.o

src/client/Items/LongSword.i: src/client/Items/LongSword.cpp.i

.PHONY : src/client/Items/LongSword.i

# target to preprocess a source file
src/client/Items/LongSword.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/LongSword.cpp.i
.PHONY : src/client/Items/LongSword.cpp.i

src/client/Items/LongSword.s: src/client/Items/LongSword.cpp.s

.PHONY : src/client/Items/LongSword.s

# target to generate assembly for a file
src/client/Items/LongSword.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/LongSword.cpp.s
.PHONY : src/client/Items/LongSword.cpp.s

src/client/Items/MagicHat.o: src/client/Items/MagicHat.cpp.o

.PHONY : src/client/Items/MagicHat.o

# target to build an object file
src/client/Items/MagicHat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/MagicHat.cpp.o
.PHONY : src/client/Items/MagicHat.cpp.o

src/client/Items/MagicHat.i: src/client/Items/MagicHat.cpp.i

.PHONY : src/client/Items/MagicHat.i

# target to preprocess a source file
src/client/Items/MagicHat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/MagicHat.cpp.i
.PHONY : src/client/Items/MagicHat.cpp.i

src/client/Items/MagicHat.s: src/client/Items/MagicHat.cpp.s

.PHONY : src/client/Items/MagicHat.s

# target to generate assembly for a file
src/client/Items/MagicHat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/MagicHat.cpp.s
.PHONY : src/client/Items/MagicHat.cpp.s

src/client/Items/MerchantBody.o: src/client/Items/MerchantBody.cpp.o

.PHONY : src/client/Items/MerchantBody.o

# target to build an object file
src/client/Items/MerchantBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/MerchantBody.cpp.o
.PHONY : src/client/Items/MerchantBody.cpp.o

src/client/Items/MerchantBody.i: src/client/Items/MerchantBody.cpp.i

.PHONY : src/client/Items/MerchantBody.i

# target to preprocess a source file
src/client/Items/MerchantBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/MerchantBody.cpp.i
.PHONY : src/client/Items/MerchantBody.cpp.i

src/client/Items/MerchantBody.s: src/client/Items/MerchantBody.cpp.s

.PHONY : src/client/Items/MerchantBody.s

# target to generate assembly for a file
src/client/Items/MerchantBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/MerchantBody.cpp.s
.PHONY : src/client/Items/MerchantBody.cpp.s

src/client/Items/PlateArmor.o: src/client/Items/PlateArmor.cpp.o

.PHONY : src/client/Items/PlateArmor.o

# target to build an object file
src/client/Items/PlateArmor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PlateArmor.cpp.o
.PHONY : src/client/Items/PlateArmor.cpp.o

src/client/Items/PlateArmor.i: src/client/Items/PlateArmor.cpp.i

.PHONY : src/client/Items/PlateArmor.i

# target to preprocess a source file
src/client/Items/PlateArmor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PlateArmor.cpp.i
.PHONY : src/client/Items/PlateArmor.cpp.i

src/client/Items/PlateArmor.s: src/client/Items/PlateArmor.cpp.s

.PHONY : src/client/Items/PlateArmor.s

# target to generate assembly for a file
src/client/Items/PlateArmor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PlateArmor.cpp.s
.PHONY : src/client/Items/PlateArmor.cpp.s

src/client/Items/PriestBody.o: src/client/Items/PriestBody.cpp.o

.PHONY : src/client/Items/PriestBody.o

# target to build an object file
src/client/Items/PriestBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PriestBody.cpp.o
.PHONY : src/client/Items/PriestBody.cpp.o

src/client/Items/PriestBody.i: src/client/Items/PriestBody.cpp.i

.PHONY : src/client/Items/PriestBody.i

# target to preprocess a source file
src/client/Items/PriestBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PriestBody.cpp.i
.PHONY : src/client/Items/PriestBody.cpp.i

src/client/Items/PriestBody.s: src/client/Items/PriestBody.cpp.s

.PHONY : src/client/Items/PriestBody.s

# target to generate assembly for a file
src/client/Items/PriestBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PriestBody.cpp.s
.PHONY : src/client/Items/PriestBody.cpp.s

src/client/Items/PriestHead.o: src/client/Items/PriestHead.cpp.o

.PHONY : src/client/Items/PriestHead.o

# target to build an object file
src/client/Items/PriestHead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PriestHead.cpp.o
.PHONY : src/client/Items/PriestHead.cpp.o

src/client/Items/PriestHead.i: src/client/Items/PriestHead.cpp.i

.PHONY : src/client/Items/PriestHead.i

# target to preprocess a source file
src/client/Items/PriestHead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PriestHead.cpp.i
.PHONY : src/client/Items/PriestHead.cpp.i

src/client/Items/PriestHead.s: src/client/Items/PriestHead.cpp.s

.PHONY : src/client/Items/PriestHead.s

# target to generate assembly for a file
src/client/Items/PriestHead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/PriestHead.cpp.s
.PHONY : src/client/Items/PriestHead.cpp.s

src/client/Items/RedCommonBody.o: src/client/Items/RedCommonBody.cpp.o

.PHONY : src/client/Items/RedCommonBody.o

# target to build an object file
src/client/Items/RedCommonBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/RedCommonBody.cpp.o
.PHONY : src/client/Items/RedCommonBody.cpp.o

src/client/Items/RedCommonBody.i: src/client/Items/RedCommonBody.cpp.i

.PHONY : src/client/Items/RedCommonBody.i

# target to preprocess a source file
src/client/Items/RedCommonBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/RedCommonBody.cpp.i
.PHONY : src/client/Items/RedCommonBody.cpp.i

src/client/Items/RedCommonBody.s: src/client/Items/RedCommonBody.cpp.s

.PHONY : src/client/Items/RedCommonBody.s

# target to generate assembly for a file
src/client/Items/RedCommonBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/RedCommonBody.cpp.s
.PHONY : src/client/Items/RedCommonBody.cpp.s

src/client/Items/SimpleArc.o: src/client/Items/SimpleArc.cpp.o

.PHONY : src/client/Items/SimpleArc.o

# target to build an object file
src/client/Items/SimpleArc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SimpleArc.cpp.o
.PHONY : src/client/Items/SimpleArc.cpp.o

src/client/Items/SimpleArc.i: src/client/Items/SimpleArc.cpp.i

.PHONY : src/client/Items/SimpleArc.i

# target to preprocess a source file
src/client/Items/SimpleArc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SimpleArc.cpp.i
.PHONY : src/client/Items/SimpleArc.cpp.i

src/client/Items/SimpleArc.s: src/client/Items/SimpleArc.cpp.s

.PHONY : src/client/Items/SimpleArc.s

# target to generate assembly for a file
src/client/Items/SimpleArc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SimpleArc.cpp.s
.PHONY : src/client/Items/SimpleArc.cpp.s

src/client/Items/SkeletonBody.o: src/client/Items/SkeletonBody.cpp.o

.PHONY : src/client/Items/SkeletonBody.o

# target to build an object file
src/client/Items/SkeletonBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SkeletonBody.cpp.o
.PHONY : src/client/Items/SkeletonBody.cpp.o

src/client/Items/SkeletonBody.i: src/client/Items/SkeletonBody.cpp.i

.PHONY : src/client/Items/SkeletonBody.i

# target to preprocess a source file
src/client/Items/SkeletonBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SkeletonBody.cpp.i
.PHONY : src/client/Items/SkeletonBody.cpp.i

src/client/Items/SkeletonBody.s: src/client/Items/SkeletonBody.cpp.s

.PHONY : src/client/Items/SkeletonBody.s

# target to generate assembly for a file
src/client/Items/SkeletonBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SkeletonBody.cpp.s
.PHONY : src/client/Items/SkeletonBody.cpp.s

src/client/Items/SpiderBody.o: src/client/Items/SpiderBody.cpp.o

.PHONY : src/client/Items/SpiderBody.o

# target to build an object file
src/client/Items/SpiderBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SpiderBody.cpp.o
.PHONY : src/client/Items/SpiderBody.cpp.o

src/client/Items/SpiderBody.i: src/client/Items/SpiderBody.cpp.i

.PHONY : src/client/Items/SpiderBody.i

# target to preprocess a source file
src/client/Items/SpiderBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SpiderBody.cpp.i
.PHONY : src/client/Items/SpiderBody.cpp.i

src/client/Items/SpiderBody.s: src/client/Items/SpiderBody.cpp.s

.PHONY : src/client/Items/SpiderBody.s

# target to generate assembly for a file
src/client/Items/SpiderBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/SpiderBody.cpp.s
.PHONY : src/client/Items/SpiderBody.cpp.s

src/client/Items/TurtleShield.o: src/client/Items/TurtleShield.cpp.o

.PHONY : src/client/Items/TurtleShield.o

# target to build an object file
src/client/Items/TurtleShield.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/TurtleShield.cpp.o
.PHONY : src/client/Items/TurtleShield.cpp.o

src/client/Items/TurtleShield.i: src/client/Items/TurtleShield.cpp.i

.PHONY : src/client/Items/TurtleShield.i

# target to preprocess a source file
src/client/Items/TurtleShield.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/TurtleShield.cpp.i
.PHONY : src/client/Items/TurtleShield.cpp.i

src/client/Items/TurtleShield.s: src/client/Items/TurtleShield.cpp.s

.PHONY : src/client/Items/TurtleShield.s

# target to generate assembly for a file
src/client/Items/TurtleShield.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/TurtleShield.cpp.s
.PHONY : src/client/Items/TurtleShield.cpp.s

src/client/Items/ZombieBody.o: src/client/Items/ZombieBody.cpp.o

.PHONY : src/client/Items/ZombieBody.o

# target to build an object file
src/client/Items/ZombieBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ZombieBody.cpp.o
.PHONY : src/client/Items/ZombieBody.cpp.o

src/client/Items/ZombieBody.i: src/client/Items/ZombieBody.cpp.i

.PHONY : src/client/Items/ZombieBody.i

# target to preprocess a source file
src/client/Items/ZombieBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ZombieBody.cpp.i
.PHONY : src/client/Items/ZombieBody.cpp.i

src/client/Items/ZombieBody.s: src/client/Items/ZombieBody.cpp.s

.PHONY : src/client/Items/ZombieBody.s

# target to generate assembly for a file
src/client/Items/ZombieBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ZombieBody.cpp.s
.PHONY : src/client/Items/ZombieBody.cpp.s

src/client/Items/ZombieHead.o: src/client/Items/ZombieHead.cpp.o

.PHONY : src/client/Items/ZombieHead.o

# target to build an object file
src/client/Items/ZombieHead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ZombieHead.cpp.o
.PHONY : src/client/Items/ZombieHead.cpp.o

src/client/Items/ZombieHead.i: src/client/Items/ZombieHead.cpp.i

.PHONY : src/client/Items/ZombieHead.i

# target to preprocess a source file
src/client/Items/ZombieHead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ZombieHead.cpp.i
.PHONY : src/client/Items/ZombieHead.cpp.i

src/client/Items/ZombieHead.s: src/client/Items/ZombieHead.cpp.s

.PHONY : src/client/Items/ZombieHead.s

# target to generate assembly for a file
src/client/Items/ZombieHead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Items/ZombieHead.cpp.s
.PHONY : src/client/Items/ZombieHead.cpp.s

src/client/Merchant.o: src/client/Merchant.cpp.o

.PHONY : src/client/Merchant.o

# target to build an object file
src/client/Merchant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Merchant.cpp.o
.PHONY : src/client/Merchant.cpp.o

src/client/Merchant.i: src/client/Merchant.cpp.i

.PHONY : src/client/Merchant.i

# target to preprocess a source file
src/client/Merchant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Merchant.cpp.i
.PHONY : src/client/Merchant.cpp.i

src/client/Merchant.s: src/client/Merchant.cpp.s

.PHONY : src/client/Merchant.s

# target to generate assembly for a file
src/client/Merchant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Merchant.cpp.s
.PHONY : src/client/Merchant.cpp.s

src/client/Music.o: src/client/Music.cpp.o

.PHONY : src/client/Music.o

# target to build an object file
src/client/Music.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Music.cpp.o
.PHONY : src/client/Music.cpp.o

src/client/Music.i: src/client/Music.cpp.i

.PHONY : src/client/Music.i

# target to preprocess a source file
src/client/Music.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Music.cpp.i
.PHONY : src/client/Music.cpp.i

src/client/Music.s: src/client/Music.cpp.s

.PHONY : src/client/Music.s

# target to generate assembly for a file
src/client/Music.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Music.cpp.s
.PHONY : src/client/Music.cpp.s

src/client/MusicManager.o: src/client/MusicManager.cpp.o

.PHONY : src/client/MusicManager.o

# target to build an object file
src/client/MusicManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MusicManager.cpp.o
.PHONY : src/client/MusicManager.cpp.o

src/client/MusicManager.i: src/client/MusicManager.cpp.i

.PHONY : src/client/MusicManager.i

# target to preprocess a source file
src/client/MusicManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MusicManager.cpp.i
.PHONY : src/client/MusicManager.cpp.i

src/client/MusicManager.s: src/client/MusicManager.cpp.s

.PHONY : src/client/MusicManager.s

# target to generate assembly for a file
src/client/MusicManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MusicManager.cpp.s
.PHONY : src/client/MusicManager.cpp.s

src/client/Player.o: src/client/Player.cpp.o

.PHONY : src/client/Player.o

# target to build an object file
src/client/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Player.cpp.o
.PHONY : src/client/Player.cpp.o

src/client/Player.i: src/client/Player.cpp.i

.PHONY : src/client/Player.i

# target to preprocess a source file
src/client/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Player.cpp.i
.PHONY : src/client/Player.cpp.i

src/client/Player.s: src/client/Player.cpp.s

.PHONY : src/client/Player.s

# target to generate assembly for a file
src/client/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Player.cpp.s
.PHONY : src/client/Player.cpp.s

src/client/PlayerInfo.o: src/client/PlayerInfo.cpp.o

.PHONY : src/client/PlayerInfo.o

# target to build an object file
src/client/PlayerInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/PlayerInfo.cpp.o
.PHONY : src/client/PlayerInfo.cpp.o

src/client/PlayerInfo.i: src/client/PlayerInfo.cpp.i

.PHONY : src/client/PlayerInfo.i

# target to preprocess a source file
src/client/PlayerInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/PlayerInfo.cpp.i
.PHONY : src/client/PlayerInfo.cpp.i

src/client/PlayerInfo.s: src/client/PlayerInfo.cpp.s

.PHONY : src/client/PlayerInfo.s

# target to generate assembly for a file
src/client/PlayerInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/PlayerInfo.cpp.s
.PHONY : src/client/PlayerInfo.cpp.s

src/client/Point.o: src/client/Point.cpp.o

.PHONY : src/client/Point.o

# target to build an object file
src/client/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Point.cpp.o
.PHONY : src/client/Point.cpp.o

src/client/Point.i: src/client/Point.cpp.i

.PHONY : src/client/Point.i

# target to preprocess a source file
src/client/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Point.cpp.i
.PHONY : src/client/Point.cpp.i

src/client/Point.s: src/client/Point.cpp.s

.PHONY : src/client/Point.s

# target to generate assembly for a file
src/client/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Point.cpp.s
.PHONY : src/client/Point.cpp.s

src/client/Presentation.o: src/client/Presentation.cpp.o

.PHONY : src/client/Presentation.o

# target to build an object file
src/client/Presentation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Presentation.cpp.o
.PHONY : src/client/Presentation.cpp.o

src/client/Presentation.i: src/client/Presentation.cpp.i

.PHONY : src/client/Presentation.i

# target to preprocess a source file
src/client/Presentation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Presentation.cpp.i
.PHONY : src/client/Presentation.cpp.i

src/client/Presentation.s: src/client/Presentation.cpp.s

.PHONY : src/client/Presentation.s

# target to generate assembly for a file
src/client/Presentation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Presentation.cpp.s
.PHONY : src/client/Presentation.cpp.s

src/client/Priest.o: src/client/Priest.cpp.o

.PHONY : src/client/Priest.o

# target to build an object file
src/client/Priest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Priest.cpp.o
.PHONY : src/client/Priest.cpp.o

src/client/Priest.i: src/client/Priest.cpp.i

.PHONY : src/client/Priest.i

# target to preprocess a source file
src/client/Priest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Priest.cpp.i
.PHONY : src/client/Priest.cpp.i

src/client/Priest.s: src/client/Priest.cpp.s

.PHONY : src/client/Priest.s

# target to generate assembly for a file
src/client/Priest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Priest.cpp.s
.PHONY : src/client/Priest.cpp.s

src/client/Skeleton.o: src/client/Skeleton.cpp.o

.PHONY : src/client/Skeleton.o

# target to build an object file
src/client/Skeleton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Skeleton.cpp.o
.PHONY : src/client/Skeleton.cpp.o

src/client/Skeleton.i: src/client/Skeleton.cpp.i

.PHONY : src/client/Skeleton.i

# target to preprocess a source file
src/client/Skeleton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Skeleton.cpp.i
.PHONY : src/client/Skeleton.cpp.i

src/client/Skeleton.s: src/client/Skeleton.cpp.s

.PHONY : src/client/Skeleton.s

# target to generate assembly for a file
src/client/Skeleton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Skeleton.cpp.s
.PHONY : src/client/Skeleton.cpp.s

src/client/Spider.o: src/client/Spider.cpp.o

.PHONY : src/client/Spider.o

# target to build an object file
src/client/Spider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Spider.cpp.o
.PHONY : src/client/Spider.cpp.o

src/client/Spider.i: src/client/Spider.cpp.i

.PHONY : src/client/Spider.i

# target to preprocess a source file
src/client/Spider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Spider.cpp.i
.PHONY : src/client/Spider.cpp.i

src/client/Spider.s: src/client/Spider.cpp.s

.PHONY : src/client/Spider.s

# target to generate assembly for a file
src/client/Spider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Spider.cpp.s
.PHONY : src/client/Spider.cpp.s

src/client/Texture.o: src/client/Texture.cpp.o

.PHONY : src/client/Texture.o

# target to build an object file
src/client/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Texture.cpp.o
.PHONY : src/client/Texture.cpp.o

src/client/Texture.i: src/client/Texture.cpp.i

.PHONY : src/client/Texture.i

# target to preprocess a source file
src/client/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Texture.cpp.i
.PHONY : src/client/Texture.cpp.i

src/client/Texture.s: src/client/Texture.cpp.s

.PHONY : src/client/Texture.s

# target to generate assembly for a file
src/client/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Texture.cpp.s
.PHONY : src/client/Texture.cpp.s

src/client/TextureManager.o: src/client/TextureManager.cpp.o

.PHONY : src/client/TextureManager.o

# target to build an object file
src/client/TextureManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/TextureManager.cpp.o
.PHONY : src/client/TextureManager.cpp.o

src/client/TextureManager.i: src/client/TextureManager.cpp.i

.PHONY : src/client/TextureManager.i

# target to preprocess a source file
src/client/TextureManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/TextureManager.cpp.i
.PHONY : src/client/TextureManager.cpp.i

src/client/TextureManager.s: src/client/TextureManager.cpp.s

.PHONY : src/client/TextureManager.s

# target to generate assembly for a file
src/client/TextureManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/TextureManager.cpp.s
.PHONY : src/client/TextureManager.cpp.s

src/client/Tile.o: src/client/Tile.cpp.o

.PHONY : src/client/Tile.o

# target to build an object file
src/client/Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Tile.cpp.o
.PHONY : src/client/Tile.cpp.o

src/client/Tile.i: src/client/Tile.cpp.i

.PHONY : src/client/Tile.i

# target to preprocess a source file
src/client/Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Tile.cpp.i
.PHONY : src/client/Tile.cpp.i

src/client/Tile.s: src/client/Tile.cpp.s

.PHONY : src/client/Tile.s

# target to generate assembly for a file
src/client/Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Tile.cpp.s
.PHONY : src/client/Tile.cpp.s

src/client/Window.o: src/client/Window.cpp.o

.PHONY : src/client/Window.o

# target to build an object file
src/client/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Window.cpp.o
.PHONY : src/client/Window.cpp.o

src/client/Window.i: src/client/Window.cpp.i

.PHONY : src/client/Window.i

# target to preprocess a source file
src/client/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Window.cpp.i
.PHONY : src/client/Window.cpp.i

src/client/Window.s: src/client/Window.cpp.s

.PHONY : src/client/Window.s

# target to generate assembly for a file
src/client/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Window.cpp.s
.PHONY : src/client/Window.cpp.s

src/client/Zombie.o: src/client/Zombie.cpp.o

.PHONY : src/client/Zombie.o

# target to build an object file
src/client/Zombie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Zombie.cpp.o
.PHONY : src/client/Zombie.cpp.o

src/client/Zombie.i: src/client/Zombie.cpp.i

.PHONY : src/client/Zombie.i

# target to preprocess a source file
src/client/Zombie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Zombie.cpp.i
.PHONY : src/client/Zombie.cpp.i

src/client/Zombie.s: src/client/Zombie.cpp.s

.PHONY : src/client/Zombie.s

# target to generate assembly for a file
src/client/Zombie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Zombie.cpp.s
.PHONY : src/client/Zombie.cpp.s

src/client/characterStates/DeadState.o: src/client/characterStates/DeadState.cpp.o

.PHONY : src/client/characterStates/DeadState.o

# target to build an object file
src/client/characterStates/DeadState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/DeadState.cpp.o
.PHONY : src/client/characterStates/DeadState.cpp.o

src/client/characterStates/DeadState.i: src/client/characterStates/DeadState.cpp.i

.PHONY : src/client/characterStates/DeadState.i

# target to preprocess a source file
src/client/characterStates/DeadState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/DeadState.cpp.i
.PHONY : src/client/characterStates/DeadState.cpp.i

src/client/characterStates/DeadState.s: src/client/characterStates/DeadState.cpp.s

.PHONY : src/client/characterStates/DeadState.s

# target to generate assembly for a file
src/client/characterStates/DeadState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/DeadState.cpp.s
.PHONY : src/client/characterStates/DeadState.cpp.s

src/client/characterStates/MoveState.o: src/client/characterStates/MoveState.cpp.o

.PHONY : src/client/characterStates/MoveState.o

# target to build an object file
src/client/characterStates/MoveState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/MoveState.cpp.o
.PHONY : src/client/characterStates/MoveState.cpp.o

src/client/characterStates/MoveState.i: src/client/characterStates/MoveState.cpp.i

.PHONY : src/client/characterStates/MoveState.i

# target to preprocess a source file
src/client/characterStates/MoveState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/MoveState.cpp.i
.PHONY : src/client/characterStates/MoveState.cpp.i

src/client/characterStates/MoveState.s: src/client/characterStates/MoveState.cpp.s

.PHONY : src/client/characterStates/MoveState.s

# target to generate assembly for a file
src/client/characterStates/MoveState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/MoveState.cpp.s
.PHONY : src/client/characterStates/MoveState.cpp.s

src/client/characterStates/StartMovingState.o: src/client/characterStates/StartMovingState.cpp.o

.PHONY : src/client/characterStates/StartMovingState.o

# target to build an object file
src/client/characterStates/StartMovingState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/StartMovingState.cpp.o
.PHONY : src/client/characterStates/StartMovingState.cpp.o

src/client/characterStates/StartMovingState.i: src/client/characterStates/StartMovingState.cpp.i

.PHONY : src/client/characterStates/StartMovingState.i

# target to preprocess a source file
src/client/characterStates/StartMovingState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/StartMovingState.cpp.i
.PHONY : src/client/characterStates/StartMovingState.cpp.i

src/client/characterStates/StartMovingState.s: src/client/characterStates/StartMovingState.cpp.s

.PHONY : src/client/characterStates/StartMovingState.s

# target to generate assembly for a file
src/client/characterStates/StartMovingState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/StartMovingState.cpp.s
.PHONY : src/client/characterStates/StartMovingState.cpp.s

src/client/characterStates/StillState.o: src/client/characterStates/StillState.cpp.o

.PHONY : src/client/characterStates/StillState.o

# target to build an object file
src/client/characterStates/StillState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/StillState.cpp.o
.PHONY : src/client/characterStates/StillState.cpp.o

src/client/characterStates/StillState.i: src/client/characterStates/StillState.cpp.i

.PHONY : src/client/characterStates/StillState.i

# target to preprocess a source file
src/client/characterStates/StillState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/StillState.cpp.i
.PHONY : src/client/characterStates/StillState.cpp.i

src/client/characterStates/StillState.s: src/client/characterStates/StillState.cpp.s

.PHONY : src/client/characterStates/StillState.s

# target to generate assembly for a file
src/client/characterStates/StillState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/characterStates/StillState.cpp.s
.PHONY : src/client/characterStates/StillState.cpp.s

src/client/client_main.o: src/client/client_main.cpp.o

.PHONY : src/client/client_main.o

# target to build an object file
src/client/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.cpp.o
.PHONY : src/client/client_main.cpp.o

src/client/client_main.i: src/client/client_main.cpp.i

.PHONY : src/client/client_main.i

# target to preprocess a source file
src/client/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.cpp.i
.PHONY : src/client/client_main.cpp.i

src/client/client_main.s: src/client/client_main.cpp.s

.PHONY : src/client/client_main.s

# target to generate assembly for a file
src/client/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.cpp.s
.PHONY : src/client/client_main.cpp.s

src/common/Collider.o: src/common/Collider.cpp.o

.PHONY : src/common/Collider.o

# target to build an object file
src/common/Collider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Collider.cpp.o
.PHONY : src/common/Collider.cpp.o

src/common/Collider.i: src/common/Collider.cpp.i

.PHONY : src/common/Collider.i

# target to preprocess a source file
src/common/Collider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Collider.cpp.i
.PHONY : src/common/Collider.cpp.i

src/common/Collider.s: src/common/Collider.cpp.s

.PHONY : src/common/Collider.s

# target to generate assembly for a file
src/common/Collider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Collider.cpp.s
.PHONY : src/common/Collider.cpp.s

src/common/GameCharacter.o: src/common/GameCharacter.cpp.o

.PHONY : src/common/GameCharacter.o

# target to build an object file
src/common/GameCharacter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/GameCharacter.cpp.o
.PHONY : src/common/GameCharacter.cpp.o

src/common/GameCharacter.i: src/common/GameCharacter.cpp.i

.PHONY : src/common/GameCharacter.i

# target to preprocess a source file
src/common/GameCharacter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/GameCharacter.cpp.i
.PHONY : src/common/GameCharacter.cpp.i

src/common/GameCharacter.s: src/common/GameCharacter.cpp.s

.PHONY : src/common/GameCharacter.s

# target to generate assembly for a file
src/common/GameCharacter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/GameCharacter.cpp.s
.PHONY : src/common/GameCharacter.cpp.s

src/common/GameObject.o: src/common/GameObject.cpp.o

.PHONY : src/common/GameObject.o

# target to build an object file
src/common/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/GameObject.cpp.o
.PHONY : src/common/GameObject.cpp.o

src/common/GameObject.i: src/common/GameObject.cpp.i

.PHONY : src/common/GameObject.i

# target to preprocess a source file
src/common/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/GameObject.cpp.i
.PHONY : src/common/GameObject.cpp.i

src/common/GameObject.s: src/common/GameObject.cpp.s

.PHONY : src/common/GameObject.s

# target to generate assembly for a file
src/common/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/GameObject.cpp.s
.PHONY : src/common/GameObject.cpp.s

src/common/JsonReader.o: src/common/JsonReader.cpp.o

.PHONY : src/common/JsonReader.o

# target to build an object file
src/common/JsonReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/JsonReader.cpp.o
.PHONY : src/common/JsonReader.cpp.o

src/common/JsonReader.i: src/common/JsonReader.cpp.i

.PHONY : src/common/JsonReader.i

# target to preprocess a source file
src/common/JsonReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/JsonReader.cpp.i
.PHONY : src/common/JsonReader.cpp.i

src/common/JsonReader.s: src/common/JsonReader.cpp.s

.PHONY : src/common/JsonReader.s

# target to generate assembly for a file
src/common/JsonReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/JsonReader.cpp.s
.PHONY : src/common/JsonReader.cpp.s

src/common/MapObject.o: src/common/MapObject.cpp.o

.PHONY : src/common/MapObject.o

# target to build an object file
src/common/MapObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/MapObject.cpp.o
.PHONY : src/common/MapObject.cpp.o

src/common/MapObject.i: src/common/MapObject.cpp.i

.PHONY : src/common/MapObject.i

# target to preprocess a source file
src/common/MapObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/MapObject.cpp.i
.PHONY : src/common/MapObject.cpp.i

src/common/MapObject.s: src/common/MapObject.cpp.s

.PHONY : src/common/MapObject.s

# target to generate assembly for a file
src/common/MapObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/MapObject.cpp.s
.PHONY : src/common/MapObject.cpp.s

src/common/MapTransformer.o: src/common/MapTransformer.cpp.o

.PHONY : src/common/MapTransformer.o

# target to build an object file
src/common/MapTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/MapTransformer.cpp.o
.PHONY : src/common/MapTransformer.cpp.o

src/common/MapTransformer.i: src/common/MapTransformer.cpp.i

.PHONY : src/common/MapTransformer.i

# target to preprocess a source file
src/common/MapTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/MapTransformer.cpp.i
.PHONY : src/common/MapTransformer.cpp.i

src/common/MapTransformer.s: src/common/MapTransformer.cpp.s

.PHONY : src/common/MapTransformer.s

# target to generate assembly for a file
src/common/MapTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/MapTransformer.cpp.s
.PHONY : src/common/MapTransformer.cpp.s

src/common/ObjectLayer.o: src/common/ObjectLayer.cpp.o

.PHONY : src/common/ObjectLayer.o

# target to build an object file
src/common/ObjectLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/ObjectLayer.cpp.o
.PHONY : src/common/ObjectLayer.cpp.o

src/common/ObjectLayer.i: src/common/ObjectLayer.cpp.i

.PHONY : src/common/ObjectLayer.i

# target to preprocess a source file
src/common/ObjectLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/ObjectLayer.cpp.i
.PHONY : src/common/ObjectLayer.cpp.i

src/common/ObjectLayer.s: src/common/ObjectLayer.cpp.s

.PHONY : src/common/ObjectLayer.s

# target to generate assembly for a file
src/common/ObjectLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/ObjectLayer.cpp.s
.PHONY : src/common/ObjectLayer.cpp.s

src/common/Position.o: src/common/Position.cpp.o

.PHONY : src/common/Position.o

# target to build an object file
src/common/Position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Position.cpp.o
.PHONY : src/common/Position.cpp.o

src/common/Position.i: src/common/Position.cpp.i

.PHONY : src/common/Position.i

# target to preprocess a source file
src/common/Position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Position.cpp.i
.PHONY : src/common/Position.cpp.i

src/common/Position.s: src/common/Position.cpp.s

.PHONY : src/common/Position.s

# target to generate assembly for a file
src/common/Position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Position.cpp.s
.PHONY : src/common/Position.cpp.s

src/common/ServerProxy.o: src/common/ServerProxy.cpp.o

.PHONY : src/common/ServerProxy.o

# target to build an object file
src/common/ServerProxy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/ServerProxy.cpp.o
.PHONY : src/common/ServerProxy.cpp.o

src/common/ServerProxy.i: src/common/ServerProxy.cpp.i

.PHONY : src/common/ServerProxy.i

# target to preprocess a source file
src/common/ServerProxy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/ServerProxy.cpp.i
.PHONY : src/common/ServerProxy.cpp.i

src/common/ServerProxy.s: src/common/ServerProxy.cpp.s

.PHONY : src/common/ServerProxy.s

# target to generate assembly for a file
src/common/ServerProxy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/ServerProxy.cpp.s
.PHONY : src/common/ServerProxy.cpp.s

src/common/TileLayer.o: src/common/TileLayer.cpp.o

.PHONY : src/common/TileLayer.o

# target to build an object file
src/common/TileLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TileLayer.cpp.o
.PHONY : src/common/TileLayer.cpp.o

src/common/TileLayer.i: src/common/TileLayer.cpp.i

.PHONY : src/common/TileLayer.i

# target to preprocess a source file
src/common/TileLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TileLayer.cpp.i
.PHONY : src/common/TileLayer.cpp.i

src/common/TileLayer.s: src/common/TileLayer.cpp.s

.PHONY : src/common/TileLayer.s

# target to generate assembly for a file
src/common/TileLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TileLayer.cpp.s
.PHONY : src/common/TileLayer.cpp.s

src/common/TileSet.o: src/common/TileSet.cpp.o

.PHONY : src/common/TileSet.o

# target to build an object file
src/common/TileSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TileSet.cpp.o
.PHONY : src/common/TileSet.cpp.o

src/common/TileSet.i: src/common/TileSet.cpp.i

.PHONY : src/common/TileSet.i

# target to preprocess a source file
src/common/TileSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TileSet.cpp.i
.PHONY : src/common/TileSet.cpp.i

src/common/TileSet.s: src/common/TileSet.cpp.s

.PHONY : src/common/TileSet.s

# target to generate assembly for a file
src/common/TileSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TileSet.cpp.s
.PHONY : src/common/TileSet.cpp.s

src/common/TiledMap.o: src/common/TiledMap.cpp.o

.PHONY : src/common/TiledMap.o

# target to build an object file
src/common/TiledMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TiledMap.cpp.o
.PHONY : src/common/TiledMap.cpp.o

src/common/TiledMap.i: src/common/TiledMap.cpp.i

.PHONY : src/common/TiledMap.i

# target to preprocess a source file
src/common/TiledMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TiledMap.cpp.i
.PHONY : src/common/TiledMap.cpp.i

src/common/TiledMap.s: src/common/TiledMap.cpp.s

.PHONY : src/common/TiledMap.s

# target to generate assembly for a file
src/common/TiledMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/TiledMap.cpp.s
.PHONY : src/common/TiledMap.cpp.s

src/server/Arma.o: src/server/Arma.cpp.o

.PHONY : src/server/Arma.o

# target to build an object file
src/server/Arma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Arma.cpp.o
.PHONY : src/server/Arma.cpp.o

src/server/Arma.i: src/server/Arma.cpp.i

.PHONY : src/server/Arma.i

# target to preprocess a source file
src/server/Arma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Arma.cpp.i
.PHONY : src/server/Arma.cpp.i

src/server/Arma.s: src/server/Arma.cpp.s

.PHONY : src/server/Arma.s

# target to generate assembly for a file
src/server/Arma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Arma.cpp.s
.PHONY : src/server/Arma.cpp.s

src/server/Ataque.o: src/server/Ataque.cpp.o

.PHONY : src/server/Ataque.o

# target to build an object file
src/server/Ataque.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Ataque.cpp.o
.PHONY : src/server/Ataque.cpp.o

src/server/Ataque.i: src/server/Ataque.cpp.i

.PHONY : src/server/Ataque.i

# target to preprocess a source file
src/server/Ataque.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Ataque.cpp.i
.PHONY : src/server/Ataque.cpp.i

src/server/Ataque.s: src/server/Ataque.cpp.s

.PHONY : src/server/Ataque.s

# target to generate assembly for a file
src/server/Ataque.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Ataque.cpp.s
.PHONY : src/server/Ataque.cpp.s

src/server/Clase.o: src/server/Clase.cpp.o

.PHONY : src/server/Clase.o

# target to build an object file
src/server/Clase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Clase.cpp.o
.PHONY : src/server/Clase.cpp.o

src/server/Clase.i: src/server/Clase.cpp.i

.PHONY : src/server/Clase.i

# target to preprocess a source file
src/server/Clase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Clase.cpp.i
.PHONY : src/server/Clase.cpp.i

src/server/Clase.s: src/server/Clase.cpp.s

.PHONY : src/server/Clase.s

# target to generate assembly for a file
src/server/Clase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Clase.cpp.s
.PHONY : src/server/Clase.cpp.s

src/server/Criatura.o: src/server/Criatura.cpp.o

.PHONY : src/server/Criatura.o

# target to build an object file
src/server/Criatura.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Criatura.cpp.o
.PHONY : src/server/Criatura.cpp.o

src/server/Criatura.i: src/server/Criatura.cpp.i

.PHONY : src/server/Criatura.i

# target to preprocess a source file
src/server/Criatura.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Criatura.cpp.i
.PHONY : src/server/Criatura.cpp.i

src/server/Criatura.s: src/server/Criatura.cpp.s

.PHONY : src/server/Criatura.s

# target to generate assembly for a file
src/server/Criatura.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Criatura.cpp.s
.PHONY : src/server/Criatura.cpp.s

src/server/Defensa.o: src/server/Defensa.cpp.o

.PHONY : src/server/Defensa.o

# target to build an object file
src/server/Defensa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Defensa.cpp.o
.PHONY : src/server/Defensa.cpp.o

src/server/Defensa.i: src/server/Defensa.cpp.i

.PHONY : src/server/Defensa.i

# target to preprocess a source file
src/server/Defensa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Defensa.cpp.i
.PHONY : src/server/Defensa.cpp.i

src/server/Defensa.s: src/server/Defensa.cpp.s

.PHONY : src/server/Defensa.s

# target to generate assembly for a file
src/server/Defensa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Defensa.cpp.s
.PHONY : src/server/Defensa.cpp.s

src/server/Ecuacion.o: src/server/Ecuacion.cpp.o

.PHONY : src/server/Ecuacion.o

# target to build an object file
src/server/Ecuacion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Ecuacion.cpp.o
.PHONY : src/server/Ecuacion.cpp.o

src/server/Ecuacion.i: src/server/Ecuacion.cpp.i

.PHONY : src/server/Ecuacion.i

# target to preprocess a source file
src/server/Ecuacion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Ecuacion.cpp.i
.PHONY : src/server/Ecuacion.cpp.i

src/server/Ecuacion.s: src/server/Ecuacion.cpp.s

.PHONY : src/server/Ecuacion.s

# target to generate assembly for a file
src/server/Ecuacion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Ecuacion.cpp.s
.PHONY : src/server/Ecuacion.cpp.s

src/server/Estado.o: src/server/Estado.cpp.o

.PHONY : src/server/Estado.o

# target to build an object file
src/server/Estado.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Estado.cpp.o
.PHONY : src/server/Estado.cpp.o

src/server/Estado.i: src/server/Estado.cpp.i

.PHONY : src/server/Estado.i

# target to preprocess a source file
src/server/Estado.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Estado.cpp.i
.PHONY : src/server/Estado.cpp.i

src/server/Estado.s: src/server/Estado.cpp.s

.PHONY : src/server/Estado.s

# target to generate assembly for a file
src/server/Estado.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Estado.cpp.s
.PHONY : src/server/Estado.cpp.s

src/server/Excepciones.o: src/server/Excepciones.cpp.o

.PHONY : src/server/Excepciones.o

# target to build an object file
src/server/Excepciones.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Excepciones.cpp.o
.PHONY : src/server/Excepciones.cpp.o

src/server/Excepciones.i: src/server/Excepciones.cpp.i

.PHONY : src/server/Excepciones.i

# target to preprocess a source file
src/server/Excepciones.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Excepciones.cpp.i
.PHONY : src/server/Excepciones.cpp.i

src/server/Excepciones.s: src/server/Excepciones.cpp.s

.PHONY : src/server/Excepciones.s

# target to generate assembly for a file
src/server/Excepciones.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Excepciones.cpp.s
.PHONY : src/server/Excepciones.cpp.s

src/server/Movimiento.o: src/server/Movimiento.cpp.o

.PHONY : src/server/Movimiento.o

# target to build an object file
src/server/Movimiento.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Movimiento.cpp.o
.PHONY : src/server/Movimiento.cpp.o

src/server/Movimiento.i: src/server/Movimiento.cpp.i

.PHONY : src/server/Movimiento.i

# target to preprocess a source file
src/server/Movimiento.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Movimiento.cpp.i
.PHONY : src/server/Movimiento.cpp.i

src/server/Movimiento.s: src/server/Movimiento.cpp.s

.PHONY : src/server/Movimiento.s

# target to generate assembly for a file
src/server/Movimiento.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Movimiento.cpp.s
.PHONY : src/server/Movimiento.cpp.s

src/server/NPC.o: src/server/NPC.cpp.o

.PHONY : src/server/NPC.o

# target to build an object file
src/server/NPC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/NPC.cpp.o
.PHONY : src/server/NPC.cpp.o

src/server/NPC.i: src/server/NPC.cpp.i

.PHONY : src/server/NPC.i

# target to preprocess a source file
src/server/NPC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/NPC.cpp.i
.PHONY : src/server/NPC.cpp.i

src/server/NPC.s: src/server/NPC.cpp.s

.PHONY : src/server/NPC.s

# target to generate assembly for a file
src/server/NPC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/NPC.cpp.s
.PHONY : src/server/NPC.cpp.s

src/server/Raza.o: src/server/Raza.cpp.o

.PHONY : src/server/Raza.o

# target to build an object file
src/server/Raza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Raza.cpp.o
.PHONY : src/server/Raza.cpp.o

src/server/Raza.i: src/server/Raza.cpp.i

.PHONY : src/server/Raza.i

# target to preprocess a source file
src/server/Raza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Raza.cpp.i
.PHONY : src/server/Raza.cpp.i

src/server/Raza.s: src/server/Raza.cpp.s

.PHONY : src/server/Raza.s

# target to generate assembly for a file
src/server/Raza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/Raza.cpp.s
.PHONY : src/server/Raza.cpp.s

src/server/StatsJuego.o: src/server/StatsJuego.cpp.o

.PHONY : src/server/StatsJuego.o

# target to build an object file
src/server/StatsJuego.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/StatsJuego.cpp.o
.PHONY : src/server/StatsJuego.cpp.o

src/server/StatsJuego.i: src/server/StatsJuego.cpp.i

.PHONY : src/server/StatsJuego.i

# target to preprocess a source file
src/server/StatsJuego.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/StatsJuego.cpp.i
.PHONY : src/server/StatsJuego.cpp.i

src/server/StatsJuego.s: src/server/StatsJuego.cpp.s

.PHONY : src/server/StatsJuego.s

# target to generate assembly for a file
src/server/StatsJuego.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/StatsJuego.cpp.s
.PHONY : src/server/StatsJuego.cpp.s

src/server/testCasillero.o: src/server/testCasillero.cpp.o

.PHONY : src/server/testCasillero.o

# target to build an object file
src/server/testCasillero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/testCasillero.cpp.o
.PHONY : src/server/testCasillero.cpp.o

src/server/testCasillero.i: src/server/testCasillero.cpp.i

.PHONY : src/server/testCasillero.i

# target to preprocess a source file
src/server/testCasillero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/testCasillero.cpp.i
.PHONY : src/server/testCasillero.cpp.i

src/server/testCasillero.s: src/server/testCasillero.cpp.s

.PHONY : src/server/testCasillero.s

# target to generate assembly for a file
src/server/testCasillero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/testCasillero.cpp.s
.PHONY : src/server/testCasillero.cpp.s

src/server/testPersonaje.o: src/server/testPersonaje.cpp.o

.PHONY : src/server/testPersonaje.o

# target to build an object file
src/server/testPersonaje.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/testPersonaje.cpp.o
.PHONY : src/server/testPersonaje.cpp.o

src/server/testPersonaje.i: src/server/testPersonaje.cpp.i

.PHONY : src/server/testPersonaje.i

# target to preprocess a source file
src/server/testPersonaje.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/testPersonaje.cpp.i
.PHONY : src/server/testPersonaje.cpp.i

src/server/testPersonaje.s: src/server/testPersonaje.cpp.s

.PHONY : src/server/testPersonaje.s

# target to generate assembly for a file
src/server/testPersonaje.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server/testPersonaje.cpp.s
.PHONY : src/server/testPersonaje.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Server"
	@echo "... client"
	@echo "... src/client/Banker.o"
	@echo "... src/client/Banker.i"
	@echo "... src/client/Banker.s"
	@echo "... src/client/Camera.o"
	@echo "... src/client/Camera.i"
	@echo "... src/client/Camera.s"
	@echo "... src/client/Chrono.o"
	@echo "... src/client/Chrono.i"
	@echo "... src/client/Chrono.s"
	@echo "... src/client/Exception.o"
	@echo "... src/client/Exception.i"
	@echo "... src/client/Exception.s"
	@echo "... src/client/Font.o"
	@echo "... src/client/Font.i"
	@echo "... src/client/Font.s"
	@echo "... src/client/GameMap.o"
	@echo "... src/client/GameMap.i"
	@echo "... src/client/GameMap.s"
	@echo "... src/client/Goblin.o"
	@echo "... src/client/Goblin.i"
	@echo "... src/client/Goblin.s"
	@echo "... src/client/Items/AshStick.o"
	@echo "... src/client/Items/AshStick.i"
	@echo "... src/client/Items/AshStick.s"
	@echo "... src/client/Items/Ax.o"
	@echo "... src/client/Items/Ax.i"
	@echo "... src/client/Items/Ax.s"
	@echo "... src/client/Items/BankerBody.o"
	@echo "... src/client/Items/BankerBody.i"
	@echo "... src/client/Items/BankerBody.s"
	@echo "... src/client/Items/BlueCommonBody.o"
	@echo "... src/client/Items/BlueCommonBody.i"
	@echo "... src/client/Items/BlueCommonBody.s"
	@echo "... src/client/Items/BlueTunic.o"
	@echo "... src/client/Items/BlueTunic.i"
	@echo "... src/client/Items/BlueTunic.s"
	@echo "... src/client/Items/CompoundArc.o"
	@echo "... src/client/Items/CompoundArc.i"
	@echo "... src/client/Items/CompoundArc.s"
	@echo "... src/client/Items/Crosier.o"
	@echo "... src/client/Items/Crosier.i"
	@echo "... src/client/Items/Crosier.s"
	@echo "... src/client/Items/DwarfHead.o"
	@echo "... src/client/Items/DwarfHead.i"
	@echo "... src/client/Items/DwarfHead.s"
	@echo "... src/client/Items/ElfHead.o"
	@echo "... src/client/Items/ElfHead.i"
	@echo "... src/client/Items/ElfHead.s"
	@echo "... src/client/Items/ElficFlaute.o"
	@echo "... src/client/Items/ElficFlaute.i"
	@echo "... src/client/Items/ElficFlaute.s"
	@echo "... src/client/Items/GhostBody.o"
	@echo "... src/client/Items/GhostBody.i"
	@echo "... src/client/Items/GhostBody.s"
	@echo "... src/client/Items/GnarledStick.o"
	@echo "... src/client/Items/GnarledStick.i"
	@echo "... src/client/Items/GnarledStick.s"
	@echo "... src/client/Items/GnomeHead.o"
	@echo "... src/client/Items/GnomeHead.i"
	@echo "... src/client/Items/GnomeHead.s"
	@echo "... src/client/Items/GoblinBody.o"
	@echo "... src/client/Items/GoblinBody.i"
	@echo "... src/client/Items/GoblinBody.s"
	@echo "... src/client/Items/GreenCommonBody.o"
	@echo "... src/client/Items/GreenCommonBody.i"
	@echo "... src/client/Items/GreenCommonBody.s"
	@echo "... src/client/Items/Hammer.o"
	@echo "... src/client/Items/Hammer.i"
	@echo "... src/client/Items/Hammer.s"
	@echo "... src/client/Items/Hood.o"
	@echo "... src/client/Items/Hood.i"
	@echo "... src/client/Items/Hood.s"
	@echo "... src/client/Items/HumanHead.o"
	@echo "... src/client/Items/HumanHead.i"
	@echo "... src/client/Items/HumanHead.s"
	@echo "... src/client/Items/IronHelmet.o"
	@echo "... src/client/Items/IronHelmet.i"
	@echo "... src/client/Items/IronHelmet.s"
	@echo "... src/client/Items/IronShield.o"
	@echo "... src/client/Items/IronShield.i"
	@echo "... src/client/Items/IronShield.s"
	@echo "... src/client/Items/LeatherArmor.o"
	@echo "... src/client/Items/LeatherArmor.i"
	@echo "... src/client/Items/LeatherArmor.s"
	@echo "... src/client/Items/LongSword.o"
	@echo "... src/client/Items/LongSword.i"
	@echo "... src/client/Items/LongSword.s"
	@echo "... src/client/Items/MagicHat.o"
	@echo "... src/client/Items/MagicHat.i"
	@echo "... src/client/Items/MagicHat.s"
	@echo "... src/client/Items/MerchantBody.o"
	@echo "... src/client/Items/MerchantBody.i"
	@echo "... src/client/Items/MerchantBody.s"
	@echo "... src/client/Items/PlateArmor.o"
	@echo "... src/client/Items/PlateArmor.i"
	@echo "... src/client/Items/PlateArmor.s"
	@echo "... src/client/Items/PriestBody.o"
	@echo "... src/client/Items/PriestBody.i"
	@echo "... src/client/Items/PriestBody.s"
	@echo "... src/client/Items/PriestHead.o"
	@echo "... src/client/Items/PriestHead.i"
	@echo "... src/client/Items/PriestHead.s"
	@echo "... src/client/Items/RedCommonBody.o"
	@echo "... src/client/Items/RedCommonBody.i"
	@echo "... src/client/Items/RedCommonBody.s"
	@echo "... src/client/Items/SimpleArc.o"
	@echo "... src/client/Items/SimpleArc.i"
	@echo "... src/client/Items/SimpleArc.s"
	@echo "... src/client/Items/SkeletonBody.o"
	@echo "... src/client/Items/SkeletonBody.i"
	@echo "... src/client/Items/SkeletonBody.s"
	@echo "... src/client/Items/SpiderBody.o"
	@echo "... src/client/Items/SpiderBody.i"
	@echo "... src/client/Items/SpiderBody.s"
	@echo "... src/client/Items/TurtleShield.o"
	@echo "... src/client/Items/TurtleShield.i"
	@echo "... src/client/Items/TurtleShield.s"
	@echo "... src/client/Items/ZombieBody.o"
	@echo "... src/client/Items/ZombieBody.i"
	@echo "... src/client/Items/ZombieBody.s"
	@echo "... src/client/Items/ZombieHead.o"
	@echo "... src/client/Items/ZombieHead.i"
	@echo "... src/client/Items/ZombieHead.s"
	@echo "... src/client/Merchant.o"
	@echo "... src/client/Merchant.i"
	@echo "... src/client/Merchant.s"
	@echo "... src/client/Music.o"
	@echo "... src/client/Music.i"
	@echo "... src/client/Music.s"
	@echo "... src/client/MusicManager.o"
	@echo "... src/client/MusicManager.i"
	@echo "... src/client/MusicManager.s"
	@echo "... src/client/Player.o"
	@echo "... src/client/Player.i"
	@echo "... src/client/Player.s"
	@echo "... src/client/PlayerInfo.o"
	@echo "... src/client/PlayerInfo.i"
	@echo "... src/client/PlayerInfo.s"
	@echo "... src/client/Point.o"
	@echo "... src/client/Point.i"
	@echo "... src/client/Point.s"
	@echo "... src/client/Presentation.o"
	@echo "... src/client/Presentation.i"
	@echo "... src/client/Presentation.s"
	@echo "... src/client/Priest.o"
	@echo "... src/client/Priest.i"
	@echo "... src/client/Priest.s"
	@echo "... src/client/Skeleton.o"
	@echo "... src/client/Skeleton.i"
	@echo "... src/client/Skeleton.s"
	@echo "... src/client/Spider.o"
	@echo "... src/client/Spider.i"
	@echo "... src/client/Spider.s"
	@echo "... src/client/Texture.o"
	@echo "... src/client/Texture.i"
	@echo "... src/client/Texture.s"
	@echo "... src/client/TextureManager.o"
	@echo "... src/client/TextureManager.i"
	@echo "... src/client/TextureManager.s"
	@echo "... src/client/Tile.o"
	@echo "... src/client/Tile.i"
	@echo "... src/client/Tile.s"
	@echo "... src/client/Window.o"
	@echo "... src/client/Window.i"
	@echo "... src/client/Window.s"
	@echo "... src/client/Zombie.o"
	@echo "... src/client/Zombie.i"
	@echo "... src/client/Zombie.s"
	@echo "... src/client/characterStates/DeadState.o"
	@echo "... src/client/characterStates/DeadState.i"
	@echo "... src/client/characterStates/DeadState.s"
	@echo "... src/client/characterStates/MoveState.o"
	@echo "... src/client/characterStates/MoveState.i"
	@echo "... src/client/characterStates/MoveState.s"
	@echo "... src/client/characterStates/StartMovingState.o"
	@echo "... src/client/characterStates/StartMovingState.i"
	@echo "... src/client/characterStates/StartMovingState.s"
	@echo "... src/client/characterStates/StillState.o"
	@echo "... src/client/characterStates/StillState.i"
	@echo "... src/client/characterStates/StillState.s"
	@echo "... src/client/client_main.o"
	@echo "... src/client/client_main.i"
	@echo "... src/client/client_main.s"
	@echo "... src/common/Collider.o"
	@echo "... src/common/Collider.i"
	@echo "... src/common/Collider.s"
	@echo "... src/common/GameCharacter.o"
	@echo "... src/common/GameCharacter.i"
	@echo "... src/common/GameCharacter.s"
	@echo "... src/common/GameObject.o"
	@echo "... src/common/GameObject.i"
	@echo "... src/common/GameObject.s"
	@echo "... src/common/JsonReader.o"
	@echo "... src/common/JsonReader.i"
	@echo "... src/common/JsonReader.s"
	@echo "... src/common/MapObject.o"
	@echo "... src/common/MapObject.i"
	@echo "... src/common/MapObject.s"
	@echo "... src/common/MapTransformer.o"
	@echo "... src/common/MapTransformer.i"
	@echo "... src/common/MapTransformer.s"
	@echo "... src/common/ObjectLayer.o"
	@echo "... src/common/ObjectLayer.i"
	@echo "... src/common/ObjectLayer.s"
	@echo "... src/common/Position.o"
	@echo "... src/common/Position.i"
	@echo "... src/common/Position.s"
	@echo "... src/common/ServerProxy.o"
	@echo "... src/common/ServerProxy.i"
	@echo "... src/common/ServerProxy.s"
	@echo "... src/common/TileLayer.o"
	@echo "... src/common/TileLayer.i"
	@echo "... src/common/TileLayer.s"
	@echo "... src/common/TileSet.o"
	@echo "... src/common/TileSet.i"
	@echo "... src/common/TileSet.s"
	@echo "... src/common/TiledMap.o"
	@echo "... src/common/TiledMap.i"
	@echo "... src/common/TiledMap.s"
	@echo "... src/server/Arma.o"
	@echo "... src/server/Arma.i"
	@echo "... src/server/Arma.s"
	@echo "... src/server/Ataque.o"
	@echo "... src/server/Ataque.i"
	@echo "... src/server/Ataque.s"
	@echo "... src/server/Clase.o"
	@echo "... src/server/Clase.i"
	@echo "... src/server/Clase.s"
	@echo "... src/server/Criatura.o"
	@echo "... src/server/Criatura.i"
	@echo "... src/server/Criatura.s"
	@echo "... src/server/Defensa.o"
	@echo "... src/server/Defensa.i"
	@echo "... src/server/Defensa.s"
	@echo "... src/server/Ecuacion.o"
	@echo "... src/server/Ecuacion.i"
	@echo "... src/server/Ecuacion.s"
	@echo "... src/server/Estado.o"
	@echo "... src/server/Estado.i"
	@echo "... src/server/Estado.s"
	@echo "... src/server/Excepciones.o"
	@echo "... src/server/Excepciones.i"
	@echo "... src/server/Excepciones.s"
	@echo "... src/server/Movimiento.o"
	@echo "... src/server/Movimiento.i"
	@echo "... src/server/Movimiento.s"
	@echo "... src/server/NPC.o"
	@echo "... src/server/NPC.i"
	@echo "... src/server/NPC.s"
	@echo "... src/server/Raza.o"
	@echo "... src/server/Raza.i"
	@echo "... src/server/Raza.s"
	@echo "... src/server/StatsJuego.o"
	@echo "... src/server/StatsJuego.i"
	@echo "... src/server/StatsJuego.s"
	@echo "... src/server/testCasillero.o"
	@echo "... src/server/testCasillero.i"
	@echo "... src/server/testCasillero.s"
	@echo "... src/server/testPersonaje.o"
	@echo "... src/server/testPersonaje.i"
	@echo "... src/server/testPersonaje.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

